name: Rust (Windows Build)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable

    - name: Build (Release)
      run: cargo build --release --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Upload compiled binary
      uses: actions/upload-artifact@v4
      with:
        name: rust-windows-binary
        path: target/release/*.exe
